// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udtoraeugieokimmhzuv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkdG9yYWV1Z2llb2tpbW1oenV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI3ODE5ODksImV4cCI6MjA3ODM1Nzk4OX0.f8_CvodpKcsYi5hMbUIdRgzt8CEM8mGHQ6naJxSycfA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});